### ISSUE TITLE
Cannot open Node Shell via OpenLens

### ISSUE THREAD

**Issue by Failsafe787** [alebcay/openlens-node-pod-menu#19]
Hello,

I'm currently using OpenLens 6.4.0 beta 13 with an AWS cluster, but this problem happens since 6.3.0. 
I currently cannot open a Node Shell, as the terminal hangs on "Connetting...".

![image](https://user-images.githubusercontent.com/20112417/218196413-2f095fb5-f5c4-42c5-a5ce-301934b92d61.png)

However, the underlying node-shell pods are being created past this action, as you can see below.

![image](https://user-images.githubusercontent.com/20112417/218197039-d9391ce8-6674-4772-9b77-fa9a8b074c1d.png)

Can you check if this issue is related to the extension or Lens codebase?

Thank you!

**Comment by alebcay** [comment]
This is an issue with the Lens codebase. I opened https://github.com/lensapp/lens/issues/7091 and someone else has also separately reported https://github.com/lensapp/lens/issues/7138.

For now, you can open a pod shell on the `node-shell-*` pod and still have access to the node shell.

**Comment by Failsafe787** [comment]
Hello @alebcay,

Thanks for the check and for pointing out where the issue lies, I will close this issue.
