### ISSUE TITLE
thank you and ...

### ISSUE THREAD

**Issue by marafa-sugarcrm** [alebcay/openlens-node-pod-menu#2]
hi
thank you and was wondering if we could build these extensions?
that way we (users) can install them quicker as per these instructions https://github.com/kocyigitkim/lens-app-viewer#installation

thank you

**Comment by alebcay** [comment]
Added instructions for installing from NPM in https://github.com/alebcay/openlens-node-pod-menu/commit/cac4812ef9974614b2f282a5f5ed5206214b98f1.
