### ISSUE TITLE
Shell and Logs menus don't appear in OpenLens v6.4.0-beta.13

### ISSUE THREAD

**Issue by b-a-t** [alebcay/openlens-node-pod-menu#24]
Looking at the previous issue #15 I decided to give a try to [v6.4.0-beta.13](https://github.com/MuhammedKalkan/OpenLens/releases/tag/v6.4.0-beta.13).

Despite having `open-node-pod-menu` enabled in the Extensions I don't see relevant Shell and Logs menu for the Pods at all :(

Rolling back to 6.3.0 brings menus back without any additional moves.

**Comment by alebcay** [comment]
If you installed this extension prior while still running 6.3.0, please try uninstalling and reinstalling the extension and see if that helps.

**Comment by Bak3y** [comment]
Update - on 6.4.0-beta.16 the extension is rapidly toggling itself between enabled/disabled

**Comment by justdan96** [comment]
@Bak3y I'm not seeing any issues here, how does that behaviour affect you?

**Comment by alebcay** [comment]
> Update - on 6.4.0-beta.16 the extension is rapidly toggling itself between enabled/disabled

Please try uninstalling and reinstalling the extension and see if that helps. If the issue persists, please try deleting the OpenLens configuration directory via the steps outlined at https://github.com/alebcay/openlens-node-pod-menu/issues/15#issuecomment-1420821747.

**Comment by SamSpiri** [comment]
I managed to fix my setup. I have pop_os 22, installed openlens with app shop: flatpak openlens 6.4.0-cron.f678bf4.
Extension didn't appear after i inserted @alebcay/openlens-node-pod-menu into install text field in lens.
Then installed like this: https://github.com/alebcay/openlens-node-pod-menu/issues/3#issue-1514506747
Extension appeared disabled after openlens restart, I enabled but no log and shell buttons were visible.
Then I oppened the dev tools in lens, swithched to Console and found error:
```
BrowserConsole.js:47 [EXTENSIONS-LOADER]: can't load renderer for "@alebcay/openlens-node-pod-menu": Error: Cannot find module '/home/spiridonov/.var/app/dev.k8slens.OpenLens/config/OpenLens/node_modules/@alebcay/openlens-node-pod-menu/dist/renderer.js'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at i._resolveFilename (node:electron/js2c/renderer_init:33:1095)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at ExtensionLoader.requireExtension (https://lens.app:37329/build/lens.js?cf6d95c…:543260:20)
    at https://lens.app:37329/build/lens.js?cf6d95c…:543212:53
    at Array.map (<anonymous>) 
Object
```
Then I placed missing file to the path:
/home/spiridonov/.var/app/dev.k8slens.OpenLens/config/OpenLens/node_modules/@alebcay/openlens-node-pod-menu/dist/renderer.js
I took it from tgz file which was generated during build and installation process.

**Comment by justdan96** [comment]
With stable versions 6.4.0, .1, .2, .3, .4 and .5 now released and the extension working in these versions should this issue be closed?

**Comment by alebcay** [comment]
Upstream Lens has been fixing up a number of issues related to extension loading in the 6.4.x stable series. I think most of the issues witnessed here are probably fixed now.

For any continuing issues with extension not loading, especially after resetting Lens and/or uninstalling + reinstalling the extension, please open a new issue.
