### ISSUE TITLE
blank screen when opening a Cluster

### ISSUE THREAD

**Issue by ranma2913** [alebcay/openlens-node-pod-menu#8]
Reproduce:
1. Install openlens with homebrew `brew install --cask openlens`
2. Install `@alebcay/openlens-node-pod-menu` extension in the extensions menu.
    ![image](https://user-images.githubusercontent.com/4295880/211917715-6d5f740d-6bd4-44d9-b650-86e461d9533f.png)

4. Open a configured cluster and get blank screen
    ![image](https://user-images.githubusercontent.com/4295880/211918064-d6ba3558-3be3-4726-bef6-01385a13dd99.png)

**Comment by rlex** [comment]
i get this even without plugin installed. Seems to be lens issue.

**Comment by ranma2913** [comment]
> 

Thanks. I've downgraded to https://github.com/MuhammedKalkan/OpenLens/releases/tag/v6.2.5 and so everything worked right out of the box. I'll have to wait for a while and try v6.4 once it's GA.

**Comment by ranma2913** [comment]
Oh, I see this is tracked https://github.com/MuhammedKalkan/OpenLens/issues/81 so probably unrelated to this Plugin.
